development:
  adapter: postgresql
  encoding: unicode
  database: site_example_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: site_example_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: site_example_production
  pool: 5
  username: postgres
  password: postgres
